In [8]:
import numpy as np


# The Basics


In [17]:
a=np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [18]:
b=np.array([[1.0,8.2,5.0],[2.0,5.0,6.0]])
print(b)

[[1.  8.2 5. ]
 [2.  5.  6. ]]


In [19]:
# Get Dimension
a.ndim

1

In [20]:
b.ndim

2

In [21]:
# Get shape
a.shape
b.shape

(2, 3)

In [22]:
# Get type
a.dtype

dtype('int32')

In [23]:
# Get size
a.itemsize

4

In [24]:
# Get total size
a.nbytes

12

# Accessing/Changing specific elements,rows,column etc.

In [25]:
c=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],dtype='int32')
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
# Get a specific element [r,c]
c[1,5]


np.int32(12)

In [27]:
# Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [28]:
# Get a specific column
c[:,4]

array([ 5, 11], dtype=int32)

In [29]:
# Getting a little more fancy [startidx:endidx:step]
c[0,1:5:2]

array([2, 4], dtype=int32)

In [30]:
# Manupulating array
c[1,4]=5

In [31]:
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10  5 12]]


In [32]:
c[1,:]=5
print(c)

[[1 2 3 4 5 6]
 [5 5 5 5 5 5]]


In [33]:
c[:,2]=[2,4]

In [34]:
print(c)

[[1 2 2 4 5 6]
 [5 5 4 5 5 5]]


In [35]:
# 3d example
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element(work outside in)
d[0,1,1]

np.int64(4)

# Initializing Different type of arrays

In [37]:
# All 0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#all 1s matrix
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# any other no.
np.full((2,3),52)

array([[52, 52, 52],
       [52, 52, 52]])

In [40]:
# full_like
np.full_like(a,3)

array([3, 3, 3], dtype=int32)

In [41]:
# random decimal 
np.random.rand(2,2)

array([[0.16741565, 0.95003828],
       [0.18127407, 0.05972269]])

In [42]:
#random integer
np.random.randint(2,4,(2,2))

array([[2, 2],
       [3, 3]], dtype=int32)

In [43]:
# the identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [44]:
#repeate an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,2,0)
print(r1)

[[1 2 3]
 [1 2 3]]


In [53]:
#exercise
output=np.ones((5,5))
new=np.zeros((3,3))
new[1,1]=9
output[1:4,1:4]=new
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carefull when copying arrays

In [54]:
a=np.array([1,2,3])
b=a.copy()
b[1]=100
print(b)
print(a)

[  1 100   3]
[1 2 3]
