## Mathematics


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a**2

array([ 1,  4,  9, 16])

In [5]:
b=np.array([2,4,6,8])
b+a

array([ 3,  6,  9, 12])

In [6]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
np.cos(b)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003])

In [8]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

#### Linear algebra


In [2]:
 c=np.ones((2,3))
 print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
d=np.full((3,2),2)
np.matmul(c,d)

array([[6., 6.],
       [6., 6.]])

In [5]:
#Find the determinant
e=np.identity(3)
np.linalg.det(e)

np.float64(1.0)

#### Statistics


In [6]:
stat=np.array([[1,2,3],[4,5,6]])
np.min(stat)

np.int64(1)

In [7]:
np.max(stat)

np.int64(6)

In [8]:
np.mean(stat)

np.float64(3.5)

In [12]:
np.sum(stat)

np.int64(21)

### Reorganizing arrays

In [20]:
before=np.array([[1,2,3,4],[5,6,7,8]])
after=before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
# Vertically stacking vector
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack((v1,v2,v1,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [25]:
#horizontal stacking 
v3=np.ones((2,4))
v4=np.zeros((2,2))
np.hstack((v3,v4,v3))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

# Miscellanious

#### Load data from file


In [34]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

C:\Users\acer\AppData\Local\Temp\ipykernel_13768\4051230873.py:2: RuntimeWarning: invalid value encountered in cast
  filedata=filedata.astype('int32')


array([[          1,           2,           3,           4,           5,
                  6,           7,           8,           9, -2147483648],
       [         10,          11,          12,          13,          14,
                 15,          16,          17,          18, -2147483648],
       [         19,          20,          21,          23,          22,
                 22,          14,          15,          18,          16]],
      dtype=int32)

### Boolean masking and advance indexing


In [35]:
filedata>20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False]])

In [ ]:
## we can do indexing with list in numpy array
filedata[filedata>20]

array([21, 23, 22, 22], dtype=int32)

In [42]:
np.any(filedata>20,axis=0)

array([False, False,  True,  True,  True,  True, False, False, False,
       False])

In [43]:
np.all(filedata>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [45]:
(~(filedata>20)&(filedata<50))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False,  True,  True,  True,
         True]])

In [ ]:
# can create rectangular identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [48]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])